### PR TITLE
Updated for PM5

### PR DESCRIPTION
**Pull request by supercrafter333**

### CODE REVIEW

**Comment by NhanAZ** [comment]
~~Error: "Call to a member function getPosition() on null" (EXCEPTION) in "plugins/VanillaFishing-PM5/src/santana/fishing/entity/FishingHook" at line 250~~

**Comment by supercrafter333** [comment]
This error cannot be real because [line 250](https://github.com/SantanasWrld/VanillaFishing/pull/2/files#diff-996eedfd57bfe3b9397bddc24d1b755581260fd74588ccf2be2893842a29f324L250) wasn't changed.

**Comment by supercrafter333** [comment]
And please give me information about how to reproduce this issue.

**Comment by SantanasWrld** [comment]
💀i just got the notification for this

**Pull request merged**
